openapi: 3.1.0
info:
  title: Algorand Pera Payment API (Odoo 19 Addon)
  description: |
    HTTP and JSON endpoints provided by the Algorand Pera Payment addon
    for website checkout: payment form display and payment processing callback.
  version: 19.0.1.0

servers:
  - url: /
    description: Odoo base URL (e.g. https://localhost:8069)

paths:
  /payment/algorand_pera/form:
    get:
      summary: Display Algorand payment form
      operationId: algorand_pera_form_get
      tags: [Payment Algorand]
      security: []
      parameters:
        - name: tx_id
          in: query
          required: true
          description: Payment transaction ID (integer)
          schema: { type: string }
        - name: reference
          in: query
          required: true
          description: Transaction reference (order reference)
          schema: { type: string }
      responses:
        '200':
          description: HTML payment form page
          content:
            text/html: {}
        '302':
          description: Redirect to /shop if tx_id or reference missing or invalid

    post:
      summary: Display Algorand payment form (POST)
      operationId: algorand_pera_form_post
      tags: [Payment Algorand]
      security: []
      parameters:
        - name: tx_id
          in: query
          required: true
          schema: { type: string }
        - name: reference
          in: query
          required: true
          schema: { type: string }
      responses:
        '200':
          description: HTML payment form page
          content:
            text/html: {}
        '302':
          description: Redirect to /shop if invalid

  /payment/algorand_pera/process:
    post:
      summary: Process Algorand payment after blockchain confirmation
      operationId: algorand_pera_process
      tags: [Payment Algorand]
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tx_id:
                  type: integer
                  description: Odoo payment.transaction id
                tx_hash:
                  type: string
                  description: Algorand transaction ID (blockchain)
                sender_address:
                  type: string
                  description: Algorand address that sent the payment
                error_message:
                  type: string
                  description: Error message from frontend if payment failed
              required: [tx_id, tx_hash]
      responses:
        '200':
          description: JSON result
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      success: { type: boolean, enum: [true] }
                      tx_id: { type: string, description: Algorand tx hash }
                  - type: object
                    properties:
                      error: { type: boolean, enum: [true] }
                      message: { type: string }
                      type: { type: string, enum: [insufficient_funds, payment_error] }
        '400':
          description: Missing or invalid transaction data
